/**
 * Byte-equivalence: the declarative Gentle Humanoid tracking observations (#79)
 * must reproduce the original custom-TS classes.
 *
 * The graphs under test are the REAL output of the Python builders
 * (`gentleHumanoidObsGraphs.json`, regenerated by tests/test_gentle_humanoid_obs.py).
 * The reference implementations below are transcribed directly from the bespoke
 * `examples/demo/gentle_humanoid/observations/GentleHumanoidObservations.ts`,
 * using the same `observation/math` helpers it imports — so this checks the real
 * traced graph, evaluated by the real interpreter, against the real prior math.
 *
 * Not bit-identical: decomposing a fused double-precision computation into
 * primitives rounds each intermediate to float32, so we assert agreement within
 * a tight float tolerance (imperceptible to a trained policy). The not-ready
 * short-circuit is reproduced exactly (zeros).
 */
import { describe, expect, it } from 'vitest';

import { evaluateGraph, NodeStateStore } from '../interpreter';
import type { EvalContext } from '../interpreter';
import { Primitives } from '../primitives';
import { normalizeQuat, quatApplyInv, quatInverse, quatMultiply } from '../../observation/math';
import fixture from './gentleHumanoidObsGraphs.json';

// Column-major rot6d reference, transcribed from the original
// GentleHumanoidObservations.ts (the engine no longer ships this as an op —
// it is composed from row-major QuatToRot6d + reindex).
function quatToRot6dColumns(q: ArrayLike<number>): number[] {
  const [w, x, y, z] = normalizeQuat(q);
  const r00 = 1.0 - 2.0 * (y * y + z * z);
  const r01 = 2.0 * (x * y - w * z);
  const r10 = 2.0 * (x * y + w * z);
  const r11 = 1.0 - 2.0 * (x * x + z * z);
  const r20 = 2.0 * (x * z - w * y);
  const r21 = 2.0 * (y * z + w * x);
  return [r00, r10, r20, r01, r11, r21];
}

const STEPS: number[] = fixture.future_steps;
const GRAPHS = fixture.graphs as Record<string, { nodes: unknown[]; output: string }>;

// --- mock motion command + eval context ------------------------------------
interface MockTerm {
  isReady(): boolean;
  refRootPos: Float32Array[];
  refRootQuat: Float32Array[];
  refJointPos: Float32Array[];
  refIdx: number;
  refLen: number;
}

// Deterministic pseudo-random ref buffers (no Math.random — reproducible).
function lcg(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

function makeTerm(refIdx: number, refLen: number, nJoints: number, ready = true): MockTerm {
  const rand = lcg(42);
  const norm = (q: number[]): Float32Array => {
    const n = Math.hypot(...q) || 1;
    return new Float32Array(q.map((v) => v / n));
  };
  return {
    isReady: () => ready,
    refIdx,
    refLen,
    refRootPos: Array.from({ length: refLen }, () =>
      new Float32Array([rand() * 2 - 1, rand() * 2 - 1, rand() * 2 - 1]),
    ),
    refRootQuat: Array.from({ length: refLen }, () =>
      norm([rand() * 2 - 1, rand() * 2 - 1, rand() * 2 - 1, rand() * 2 - 1]),
    ),
    refJointPos: Array.from({ length: refLen }, () =>
      new Float32Array(Array.from({ length: nJoints }, () => rand() * 2 - 1)),
    ),
  };
}

function makeCtx(term: MockTerm | null, state: { rootQuat: Float32Array; jointPos: Float32Array }, nJoints: number): EvalContext {
  const runner = {
    getContext: () => ({ commandManager: { getTerm: (n: string) => (n === 'motion' ? term : null) } }),
    getNumActions: () => nJoints,
    getLastActions: () => new Float32Array(nJoints),
  };
  return { runner, state, params: {} } as unknown as EvalContext;
}

function evalObs(name: string, ctx: EvalContext): Float32Array {
  const out = evaluateGraph(GRAPHS[name] as never, ctx, new NodeStateStore());
  return out instanceof Float32Array ? out : new Float32Array([Number(out)]);
}

// --- reference impls transcribed from GentleHumanoidObservations.ts ---------
function clampFutureIndices(base: number, steps: number[], length: number): number[] {
  return steps.map((step) => {
    const idx = base + step;
    if (idx < 0) return 0;
    if (idx >= length) return Math.max(0, length - 1);
    return idx;
  });
}
function normalizeGravity(q: ArrayLike<number>): number[] {
  const g = quatApplyInv(q, [0, 0, -1]);
  const n = Math.hypot(g[0], g[1], g[2]) || 1.0;
  return [g[0] / n, g[1] / n, g[2] / n];
}

function refTracking(t: MockTerm, state: { rootQuat: Float32Array }, steps: number[]): Float32Array {
  if (!t.isReady()) return new Float32Array((steps.length - 1) * 3 + steps.length * 6);
  const idx = clampFutureIndices(t.refIdx, steps, t.refLen);
  const basePos = t.refRootPos[idx[0]];
  const baseQuat = t.refRootQuat[idx[0]];
  const out: number[] = [];
  for (let i = 1; i < idx.length; i++) {
    const p = t.refRootPos[idx[i]];
    const d = quatApplyInv(baseQuat, [p[0] - basePos[0], p[1] - basePos[1], p[2] - basePos[2]]);
    out.push(d[0], d[1], d[2]);
  }
  const qCurInv = quatInverse(state.rootQuat);
  for (const i of idx) out.push(...quatToRot6dColumns(quatMultiply(qCurInv, t.refRootQuat[i])));
  return Float32Array.from(out);
}
function refTargetJointPos(t: MockTerm, state: { jointPos: Float32Array }, steps: number[], nJoints: number): Float32Array {
  if (!t.isReady()) return new Float32Array(steps.length * nJoints * 2);
  const idx = clampFutureIndices(t.refIdx, steps, t.refLen);
  const out = new Float32Array(steps.length * nJoints * 2);
  let tOff = 0;
  let dOff = idx.length * nJoints;
  for (const i of idx) {
    const tgt = t.refJointPos[i];
    for (let j = 0; j < nJoints; j++) {
      out[tOff++] = tgt[j];
      out[dOff++] = tgt[j] - state.jointPos[j];
    }
  }
  return out;
}
function refTargetRootZ(t: MockTerm, steps: number[]): Float32Array {
  if (!t.isReady()) return new Float32Array(steps.length);
  const idx = clampFutureIndices(t.refIdx, steps, t.refLen);
  return Float32Array.from(idx.map((i) => t.refRootPos[i][2]));
}
function refTargetGravity(t: MockTerm, steps: number[]): Float32Array {
  if (!t.isReady()) return new Float32Array(steps.length * 3);
  const idx = clampFutureIndices(t.refIdx, steps, t.refLen);
  const out: number[] = [];
  for (const i of idx) out.push(...normalizeGravity(t.refRootQuat[i]));
  return Float32Array.from(out);
}

function expectClose(a: Float32Array, b: Float32Array, tol = 1e-5): void {
  expect(a.length).toBe(b.length);
  for (let i = 0; i < a.length; i++) expect(Math.abs(a[i] - b[i])).toBeLessThan(tol);
}

// ---------------------------------------------------------------------------
describe('Gentle Humanoid tracking obs: declarative graph == bespoke class', () => {
  const nJoints = 5;
  const refLen = 20;
  const state = { rootQuat: new Float32Array([0.9239, 0, 0.3827, 0]), jointPos: new Float32Array([0.1, -0.2, 0.3, -0.4, 0.5]) };

  // refIdx in the middle, at the start (negative steps clamp), and end (positive clamp).
  for (const refIdx of [10, 0, refLen - 1]) {
    it(`matches at refIdx=${refIdx}`, () => {
      const t = makeTerm(refIdx, refLen, nJoints);
      const ctx = makeCtx(t, state, nJoints);
      expectClose(evalObs('gentle_humanoid_tracking', ctx), refTracking(t, state, STEPS));
      expectClose(evalObs('gentle_humanoid_target_joint_pos', ctx), refTargetJointPos(t, state, STEPS, nJoints));
      expectClose(evalObs('gentle_humanoid_target_root_z', ctx), refTargetRootZ(t, STEPS));
      expectClose(evalObs('gentle_humanoid_target_projected_gravity', ctx), refTargetGravity(t, STEPS));
    });
  }

  const TRACKING_OBS = [
    'gentle_humanoid_tracking',
    'gentle_humanoid_target_joint_pos',
    'gentle_humanoid_target_root_z',
    'gentle_humanoid_target_projected_gravity',
  ];

  it('not-ready term → exact zeros (matches bespoke short-circuit)', () => {
    const t = makeTerm(10, refLen, nJoints, false);
    const ctx = makeCtx(t, state, nJoints);
    for (const name of TRACKING_OBS) {
      expect(evalObs(name, ctx).every((v) => v === 0)).toBe(true);
    }
  });

  it('no motion command → exact zeros', () => {
    const ctx = makeCtx(null, state, nJoints);
    for (const name of TRACKING_OBS) {
      expect(evalObs(name, ctx).every((v) => v === 0)).toBe(true);
    }
  });
});

// ---------------------------------------------------------------------------
describe('new DSL primitives', () => {
  const ctxWith = (term: MockTerm | null) => makeCtx(term, { rootQuat: new Float32Array([1, 0, 0, 0]), jointPos: new Float32Array(3) }, 3);

  it('Div broadcasts a scalar divisor over a vector', () => {
    const got = Primitives.Div([new Float32Array([3, 0, 4]), 2], {}, ctxWith(null), {}) as Float32Array;
    expectClose(got, new Float32Array([1.5, 0, 2]), 1e-6);
  });

  it('Sqrt is elementwise; Sum reduces to a scalar', () => {
    const s = Primitives.Sqrt([new Float32Array([9, 16])], {}, ctxWith(null), {}) as Float32Array;
    expectClose(s, new Float32Array([3, 4]), 1e-6);
    expect(Primitives.Sum([new Float32Array([3, 0, 4])], {}, ctxWith(null), {})).toBe(7);
  });

  it('Div/Sqrt/Sum compose to L2-normalize (3-4-5 → 0.6/0/0.8)', () => {
    const v = new Float32Array([3, 0, 4]);
    const sumSq = Primitives.Sum([Primitives.Mul([v, v], {}, ctxWith(null), {})], {}, ctxWith(null), {});
    const norm = Primitives.Sqrt([sumSq], {}, ctxWith(null), {});
    const got = Primitives.Div([v, norm], {}, ctxWith(null), {}) as Float32Array;
    expectClose(got, new Float32Array([0.6, 0, 0.8]), 1e-6);
  });

  it('Slice extracts a contiguous sub-range', () => {
    const v = new Float32Array([10, 11, 12, 13, 14, 15]);
    const got = Primitives.Slice([v], { start: 2, len: 3 }, ctxWith(null), {}) as Float32Array;
    expectClose(got, new Float32Array([12, 13, 14]), 1e-6);
  });

  it('TrackingRefField reads the clamped frame and falls back safely', () => {
    const t = makeTerm(0, 4, 3);
    const ctx = ctxWith(t);
    // step -2 clamps to frame 0.
    const got = Primitives.TrackingRefField([], { field: 'root_pos', step: -2 }, ctx, {}) as Float32Array;
    expectClose(got, t.refRootPos[0], 1e-6);
    // not ready → identity quat / zero vectors.
    const notReady = ctxWith(makeTerm(0, 4, 3, false));
    expect(Array.from(Primitives.TrackingRefField([], { field: 'root_quat', step: 0 }, notReady, {}) as Float32Array)).toEqual([1, 0, 0, 0]);
    expect((Primitives.TrackingRefField([], { field: 'joint_pos', step: 0 }, notReady, {}) as Float32Array).length).toBe(3);
  });

  it('TrackingIsReady reflects readiness', () => {
    expect(Primitives.TrackingIsReady([], {}, ctxWith(makeTerm(0, 4, 3, true)), {})).toBe(1);
    expect(Primitives.TrackingIsReady([], {}, ctxWith(makeTerm(0, 4, 3, false)), {})).toBe(0);
    expect(Primitives.TrackingIsReady([], {}, ctxWith(null), {})).toBe(0);
  });
});

// ---------------------------------------------------------------------------
describe('Gentle Humanoid proprioceptive obs (Slice C): declarative == bespoke', () => {
  const HISTORY_STEPS: number[] = fixture.history_steps;
  const NUM_JOINTS: number = fixture.num_joints;
  const PREV_STEPS: number = fixture.prev_action_steps;

  interface FullState {
    rootAngVel: Float32Array;
    rootQuat: Float32Array;
    jointPos: Float32Array;
    jointVel: Float32Array;
    lastActions: Float32Array;
  }

  function stateAt(t: number): FullState {
    const r = lcg(1000 + t);
    const vec = (n: number) => new Float32Array(Array.from({ length: n }, () => r() * 2 - 1));
    return {
      rootAngVel: vec(3),
      rootQuat: vec(4),
      jointPos: vec(NUM_JOINTS),
      jointVel: vec(NUM_JOINTS),
      lastActions: vec(NUM_JOINTS),
    };
  }

  function ctxOf(s: FullState): EvalContext {
    const runner = {
      getContext: () => ({ commandManager: { getTerm: () => null, getCommand: () => null } }),
      getNumActions: () => NUM_JOINTS,
      getLastActions: () => s.lastActions,
    };
    return { runner, state: s, params: {} } as unknown as EvalContext;
  }

  // Feed a state sequence through one graph, accumulating stateful History.
  function evalSequence(name: string, seq: FullState[]): Float32Array {
    const store = new NodeStateStore();
    let out: unknown = new Float32Array(0);
    for (const s of seq) out = evaluateGraph(GRAPHS[name] as never, ctxOf(s), store);
    return out as Float32Array;
  }

  // Bespoke HistoryObservation: reset fills with seq[0], then one update/step.
  function refHistory(current: (s: FullState) => Float32Array, offsets: number[], seq: FullState[]): Float32Array {
    const maxStep = Math.max(...offsets);
    const buf: Float32Array[] = Array.from({ length: maxStep + 1 }, () => current(seq[0]));
    for (let t = 1; t < seq.length; t++) {
      for (let i = buf.length - 1; i > 0; i--) buf[i] = buf[i - 1];
      buf[0] = current(seq[t]);
    }
    const out: number[] = [];
    for (const o of offsets) out.push(...buf[Math.min(o, buf.length - 1)]);
    return Float32Array.from(out);
  }

  const seq = Array.from({ length: 25 }, (_v, t) => stateAt(t));

  it('boot → [0]', () => {
    expect(Array.from(evalSequence('gentle_humanoid_boot', seq.slice(0, 1)))).toEqual([0]);
  });

  it('compliance = [enabled, enabled*force, enabled*force/0.05]', () => {
    for (const cmd of [new Float32Array([1, 15]), new Float32Array([0, 12]), new Float32Array([1, 20])]) {
      const runner = {
        getContext: () => ({
          commandManager: { getTerm: () => null, getCommand: (n: string) => (n === 'compliance' ? cmd : null) },
        }),
        getNumActions: () => NUM_JOINTS,
        getLastActions: () => new Float32Array(NUM_JOINTS),
      };
      const ctx = { runner, state: {}, params: {} } as unknown as EvalContext;
      const got = evaluateGraph(GRAPHS['gentle_humanoid_compliance'] as never, ctx, new NodeStateStore()) as Float32Array;
      const enabled = cmd[0] >= 0.5 ? 1 : 0;
      expectClose(got, new Float32Array([enabled, enabled * cmd[1], (enabled * cmd[1]) / 0.05]));
    }
  });

  it('root_ang_vel sparse history', () => {
    expectClose(evalSequence('gentle_humanoid_root_ang_vel', seq), refHistory((s) => s.rootAngVel, HISTORY_STEPS, seq));
  });

  it('projected_gravity sparse history (normalized)', () => {
    expectClose(
      evalSequence('gentle_humanoid_projected_gravity', seq),
      refHistory((s) => Float32Array.from(normalizeGravity(s.rootQuat)), HISTORY_STEPS, seq),
    );
  });

  it('joint_pos / joint_vel sparse history', () => {
    expectClose(evalSequence('gentle_humanoid_joint_pos', seq), refHistory((s) => s.jointPos, HISTORY_STEPS, seq));
    expectClose(evalSequence('gentle_humanoid_joint_vel', seq), refHistory((s) => s.jointVel, HISTORY_STEPS, seq));
  });

  it('prev_actions contiguous history', () => {
    const offsets = Array.from({ length: PREV_STEPS }, (_v, i) => i);
    expectClose(evalSequence('gentle_humanoid_prev_actions', seq), refHistory((s) => s.lastActions, offsets, seq));
  });
});
